Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 354, in _check_seekable
    f.seek(f.tell())
    ^^^^^^
AttributeError: 'int' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\Downloads\Tetris\Trainer.py", line 81, in <module>
    main()
  File "c:\Users\user\Downloads\Tetris\Trainer.py", line 33, in main
    player = DQN_Agent(1, env=env)
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Downloads\Tetris\DQN_Agent.py", line 15, in __init__
    self.DQN.load_params(parametes_path)
  File "c:\Users\user\Downloads\Tetris\DQN.py", line 38, in load_params
    self.load_state_dict(torch.load(path))
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 276, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 261, in __init__
    _check_seekable(buffer)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 357, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 350, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'int' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
